config-version: 2

name: 'salesforce_source'
version: '0.3.1'
profile: default
require-dbt-version: ">=0.19.1"

models:
  salesforce_source:
    tmp:
      materialized: view
    materialized: table
  file_format: delta

seeds:
  file_format: delta

snapshots:
  file_format: delta

vars:
  salesforce_source:
    account: "{{ source('salesforce', 'account') }}"
    opportunity: "{{ source('salesforce', 'opportunity') }}"
    user: "{{ source('salesforce', 'user') }}"
    user_role: "{{ source('salesforce', 'user_role') }}"

    # Salesforce pass through column variables
    account_pass_through_columns: []
    opportunity_pass_through_columns: []
    user_pass_through_columns: []

    # Variable to define if you are set up with Salesforce History Mode.
    using_account_history_mode_active_records: false
    using_opportunity_history_mode_active_records: false
    using_user_role_history_mode_active_records: false
    using_user_history_mode_active_records: false

    # My additional variables

    order: "{{ source('salesforce', 'order') }}"
    item: "{{ source('salesforce', 'order_item') }}"
    product: "{{ source('salesforce', 'product_2') }}"
    order_pass_through_columns: []
    item_pass_through_columns: []
    product_pass_through_columns: []
