config-version: 2

name: 'salesforce_source'
version: '0.3.1'

require-dbt-version: ">=0.20.0"

models:
  salesforce_source:
    tmp:
      materialized: view
    materialized: table

vars:
  salesforce_source:
    account: "{{ source('salesforce', 'account') }}" 
    opportunity: "{{ source('salesforce', 'opportunity') }}" 
    user: "{{ source('salesforce', 'user') }}"
    user_role: "{{ source('salesforce', 'user_role') }}"

    # Salesforce pass through column variables
    account_pass_through_columns: []
    opportunity_pass_through_columns: []
    user_pass_through_columns: []

    # Variable to define if you are set up with Salesforce History Mode.
    using_account_history_mode_active_records: false
    using_opportunity_history_mode_active_records: false
    using_user_role_history_mode_active_records: false
    using_user_history_mode_active_records: false
