default:
  target: prod
  outputs:
    prod:
      type: spark
      method: http
      schema: dev_ernest
      host: nauto-biz-prod-us.cloud.databricks.com
      token: _token_
      cluster: 1004-233546-lager607
      port: 443
      connect_timeout: 30
      connect_retries: 15
      threads: 5
