default:
  target: dev
  outputs:
    dev:
      type: spark
      method: http
      schema: dev_ernest
      host: dbc-0b1dfbf6-3cc5.cloud.databricks.com
      port: 443
      token: _token_
      cluster: 0505-153618-tours233
      connect_timeout: 30
      connect_retries: 15
      threads: 5
