version: 2

models:

  - name: stg_salesforce__account
    columns:
      - name: account_id
        tests: 
          - not_null
          - unique

  - name: stg_salesforce__opportunity
    columns:
      - name: opportunity_id
        tests: 
          - not_null
          - unique

  - name: stg_salesforce__user
    columns:
      - name: user_id
        tests: 
          - not_null
          - unique

  - name: stg_salesforce__user_role
    columns:
      - name: user_role_id
        tests: 
          - not_null
          - unique
